## Numpy 套件

In [1]:
a=[1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### Numpy 套件的ndarray型態，提供element-wise的操作

In [2]:
import numpy as np
b=np.array([1,2,3,4,5])
print(b*3)

[ 3  6  9 12 15]


In [3]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的 shape
print(b.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [4]:
print(np.zeros(6))
print(np.zeros((3,6)))
print(np.zeros((2,3,6)))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [5]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## 二維ndarray取值

In [6]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:]) #第0列元素
print(my_2d_array[1,])  #第1列元素
print(my_2d_array[:,0]) #第0欄元素
print(my_2d_array[1,1]) #第1列第1欄元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


##### 假設有六個組別"Modern","DevOps","Cloud","Big Data","Security","自我挑戰組"

#### 其參加人數分別為 56 , 8 , 19 , 14 , 6 , 71 人

In [7]:
import numpy as np
groups = ["Modern","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman = [56,8,19,14,6,71]
groups_array=np.array(groups)
ironman_array=np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


## 請問大於10人的組別有哪些?

In [8]:
#用人數去篩選組別
print(ironman_array >=10)
print(groups_array[ironman_array >=10])

[ True False  True  True False  True]
['Modern' 'Cloud' 'Big Data' '自我挑戰組']


## 除了自我挑戰組之外的組別，人數為何?

In [9]:
#用組別去篩選人數
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


## nadarray 空值 nan 無限大 inf

In [10]:
nan_array = np.array([56,8,19,14,6, np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


### 生成10組標準差常態分配(平均為0，標準差為1的常態分配)隨機變數

In [11]:
normal_samples =np.random.normal(size=10)
print(normal_samples)

[ 0.76984948  0.37596783 -0.25208238  1.63425689 -0.64724834  0.71405634
 -0.0470135  -0.95582977  0.64553675  0.47308549]


## 生成10組介於0~1之間的隨機變數

In [12]:
uniform_samples = np.random.uniform(size=10)
print(uniform_samples)

[0.23512153 0.14182754 0.61111073 0.27922056 0.5554494  0.37163569
 0.36078269 0.89206396 0.52869549 0.62015281]
